"""
Demo: Autonomous Coordination Engine.

Connects 4 agents with DIFFERENT capabilities, gives one goal, and
lets the coordinator decompose, match, and route tasks automatically.
No agent is hardcoded to any task.

Usage::

    $env:GEMINI_API_KEY = "your-key-here"
    python scripts/demo_coordination.py

    # Offline / mock mode:
    $env:WALRUSOS_USE_MOCKS = "1"
    python scripts/demo_coordination.py
"""
from __future__ import annotations

import asyncio
import os

from dotenv import load_dotenv
load_dotenv()


async def main() -> None:
    from walrusos import WalrusOS
    from walrusos.runtime.llm import get_provider
    from walrusos.integrations.connect import (
        connect_claude_code,
        connect_cursor,
        connect_gemini,
        connect_antigravity,
    )

    api_key = os.environ.get("GEMINI_API_KEY")

    runtime   = WalrusOS()
    workspace = runtime.workspace("coordination-demo")

    print("=" * 60)
    print("  WalrusOS Coordination Engine")
    print("  One goal. The engine decides who does what.")
    print("=" * 60)
    print()

    # Connect 4 agents with distinct capabilities
    print("[1] Connecting agents with different capabilities...")
    gemini_agent = await connect_gemini(workspace)
    antigravity  = await connect_antigravity(workspace)
    claude       = await connect_claude_code(workspace)
    cursor       = await connect_cursor(workspace)
    print("  Research/reasoning:    Gemini")
    print("  Planning/architecture: Antigravity")
    print("  Code/review:           Claude Code")
    print("  Code/editing:          Cursor")
    print()

    # One goal — no agent assignment, no order specified
    goal = (
        "Design a secure user authentication system using OAuth 2.0 "
        "with PKCE and JWT tokens. Research best practices, design the "
        "architecture, outline the implementation, and review for security."
    )

    print(f"[2] Goal: {goal[:70]}...")
    print()

    # Use Gemini if key available, otherwise stub
    llm = get_provider("auto", api_key=api_key)
    provider_name = type(llm).__name__
    print(f"[3] LLM: {provider_name}")
    print()
    print("[4] Coordinator decomposing and routing tasks...")
    print()

    def on_task(task) -> None:
        agent_name = task.assigned_to_name or "?"
        print(f"    [{agent_name:12}] {task.title[:50]} - done")

    result = await workspace.coordinate(
        goal=goal,
        llm=llm,
        on_task_complete=on_task,
    )

    print()
    print("=" * 60)
    print(f"  Tasks completed: {result.tasks_completed}/{len(result.plan.tasks)}")
    print(f"  Agents used:     {len(result.agents_used)}")
    print(f"  Duration:        {result.duration_seconds:.1f}s")
    print(f"  Completed:       {result.completed}")
    print()
    print("  Execution Plan (auto-generated by coordinator):")
    for i, task in enumerate(result.plan.tasks, 1):
        deps = f" (needs: {len(task.depends_on)})" if task.depends_on else ""
        status = "done" if task.status == "done" else task.status
        print(
            f"    {i}. [{status:8}] {task.title[:45]}"
            f"  -> {task.required_capability}"
            f"  [{task.assigned_to_name or '?'}]{deps}"
        )
    print()
    print(f"  Summary:")
    for line in result.final_summary.splitlines():
        print(f"    {line}")
    print()
    print(f"  Blobs on Walrus:  {len(result.blob_ids)}")
    print(f"  Anchors on Sui:   {len(result.sui_anchors)}")
    print()
    print("  No agent was hardcoded. The coordinator matched tasks")
    print("  to capabilities and executed autonomously.")
    print("=" * 60)

    for agent in [gemini_agent, antigravity, claude, cursor]:
        await agent.go_offline()


if __name__ == "__main__":
    asyncio.run(main())
